/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, Outlines } from '@react-three/drei'
import { useThree } from '@react-three/fiber'

export function BrandTextr3f(props) {
  const { nodes, materials } = useGLTF('/models/sharper_brands.glb')
  const { width, height } = useThree((state) => state.viewport)

  const textureLoader = new THREE.TextureLoader();

  const bakedTexture_brands = textureLoader.load('/images/ReBuild_texture_brand.jpg');
  bakedTexture_brands.flipY = false;
  bakedTexture_brands.colorSpace = THREE.SRGBColorSpace;
  
  const white = new THREE.MeshBasicMaterial({ map: bakedTexture_brands})
  const outlineMaterial = new THREE.MeshBasicMaterial({ color: "black" });

  return (
    <group {...props} dispose={null} position={[0.62,-0.64,0.48]} rotation-z={-Math.PI/24} rotation-y={Math.PI/85} rotation-x={Math.PI/30} scale-x={1.1} scale-z={0.93} scale-y={1.09}>
      <group name="Scene">
        <group name="BRANDS">
          <mesh
            name="Text002"
            castShadow
            receiveShadow
            geometry={nodes.Text002.geometry}
            material={white}
          >
            </mesh>
          <mesh
            name="Text002_1"
            castShadow
            receiveShadow
            geometry={nodes.Text002_1.geometry}
            material={outlineMaterial}
          >
            </mesh>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Outlines_brand.glb')
